api_platform:
    enable_swagger_ui: false
    enable_re_doc: false

    collection:
        pagination:
            enabled: true
            items_per_page: 10
            page_parameter_name: 'page'
            items_per_page_parameter_name: 'items'

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    patch_formats:
        json: ['application/merge-patch+json']